basePath: /
definitions:
  github_com_gulizay91_go-rest-api_pkg_models.Gender:
    enum:
    - female
    - male
    - non-binary
    - intersex
    type: string
    x-enum-varnames:
    - Female
    - Male
    - NonBinary
    - Intersex
  github_com_gulizay91_go-rest-api_pkg_models.Language:
    enum:
    - tr
    - eng
    type: string
    x-enum-varnames:
    - TR
    - ENG
  github_com_gulizay91_go-rest-api_pkg_models.Media:
    properties:
      images:
        items:
          type: string
        type: array
    required:
    - images
    type: object
  github_com_gulizay91_go-rest-api_pkg_models.ServiceResponseModel:
    properties:
      data: {}
      errorCode:
        type: string
      message:
        type: string
      statusCode:
        type: integer
      success:
        type: boolean
    type: object
  github_com_gulizay91_go-rest-api_pkg_models.UserModel:
    properties:
      birthDate:
        type: string
      createdDate:
        type: string
      email:
        type: string
      firstName:
        maxLength: 50
        type: string
      gender:
        allOf:
        - $ref: '#/definitions/github_com_gulizay91_go-rest-api_pkg_models.Gender'
        example: female
      languages:
        items:
          $ref: '#/definitions/github_com_gulizay91_go-rest-api_pkg_models.Language'
        type: array
      lastName:
        maxLength: 50
        type: string
      media:
        $ref: '#/definitions/github_com_gulizay91_go-rest-api_pkg_models.Media'
      phoneNumber:
        type: string
      subId:
        type: string
      updatedDate:
        type: string
    required:
    - birthDate
    - email
    - firstName
    - lastName
    - subId
    type: object
host: localhost:8091
info:
  contact:
    email: gulizay91@gmail.com
    name: GulizAY
    url: https://github.com/gulizay91
  description: Go - RESTful
  license:
    name: MIT License
    url: https://opensource.org/licenses/MIT
  termsOfService: https://swagger.io/terms/
  title: Go Rest API Starter Doc
  version: "1.0"
paths:
  /api/v1/user:
    post:
      consumes:
      - '*/*'
      description: create user
      parameters:
      - description: User
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/github_com_gulizay91_go-rest-api_pkg_models.UserModel'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_gulizay91_go-rest-api_pkg_models.ServiceResponseModel'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_gulizay91_go-rest-api_pkg_models.ServiceResponseModel'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/github_com_gulizay91_go-rest-api_pkg_models.ServiceResponseModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_gulizay91_go-rest-api_pkg_models.ServiceResponseModel'
      summary: create user
      tags:
      - users
  /api/v1/user/{id}:
    delete:
      consumes:
      - '*/*'
      description: delete user
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: delete user
      tags:
      - users
  /api/v1/user/{subId}:
    get:
      consumes:
      - '*/*'
      description: get user
      parameters:
      - description: subId
        in: path
        name: subId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_gulizay91_go-rest-api_pkg_models.ServiceResponseModel'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_gulizay91_go-rest-api_pkg_models.ServiceResponseModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_gulizay91_go-rest-api_pkg_models.ServiceResponseModel'
      summary: get user
      tags:
      - users
  /api/v1/user/{subId}/media:
    get:
      consumes:
      - application/json
      description: get user's images
      parameters:
      - description: subId
        in: path
        name: subId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_gulizay91_go-rest-api_pkg_models.ServiceResponseModel'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_gulizay91_go-rest-api_pkg_models.ServiceResponseModel'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_gulizay91_go-rest-api_pkg_models.ServiceResponseModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_gulizay91_go-rest-api_pkg_models.ServiceResponseModel'
      summary: get images
      tags:
      - users
  /api/v1/user/{subId}/upload-media:
    patch:
      consumes:
      - multipart/form-data
      description: upload user's images
      parameters:
      - description: subId
        in: path
        name: subId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_gulizay91_go-rest-api_pkg_models.ServiceResponseModel'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_gulizay91_go-rest-api_pkg_models.ServiceResponseModel'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_gulizay91_go-rest-api_pkg_models.ServiceResponseModel'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_gulizay91_go-rest-api_pkg_models.ServiceResponseModel'
      summary: upload images
      tags:
      - users
  /health:
    get:
      consumes:
      - '*/*'
      description: get the status of server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show the status of server.
      tags:
      - root
schemes:
- http
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Bearer-Token
    type: apiKey
swagger: "2.0"
