apiVersion: v1
kind: Service
metadata:
  name: go-rest-api
spec:
  selector:
    app: go-rest-api
  ports:
    - protocol: TCP
      port: 80 # service cluster port
      targetPort: 8091 # application port from dockerfile
  #type: ClusterIP # internal application
  type: LoadBalancer # external connectivity application and production environment, high availability and scalability
  #type: NodePort # external connectivity application

  